#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
ip=$3

sudo yunohost app checkurl $domain$path -a cops
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

sudo apt-get install php5-gd php5-sqlite

# Copy of sources files
final_path=/var/www/cops
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo mkdir $final_path/tmp
sudo chmod 775 -R $final_path
sudo chown -R www-data:www-data $final_path

# Prepare data directory
data_path=/home/yunohost.app/cops
sudo mkdir -p $data_path
sudo chown -hR www-data:www-data $data_path
sudo chown www-data:www-data $data_path
sudo chmod 755 $data_path
sudo chmod -R 770 $data_path

# Configure Nginx and reload
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/jeedom.conf
sudo service nginx reload

# Configure COPS
sudo cp ../conf/config_local.php $final_path/config_local.php
sudo sed -i "s@DATAPATH@$data_path@g" final_path/config_local.php
